      - name: Build APK
        run: |
          GRADLEW=$(find project -type f -name gradlew | head -n 1)

          if [ -z "$GRADLEW" ]; then
            echo "ERROR: gradlew tidak ditemukan!"
            echo "Isi folder project:"
            find project -maxdepth 3 -type f | head -n 50
            exit 1
          fi

          echo "Gradle wrapper found at: $GRADLEW"

          chmod +x "$GRADLEW"

          PROJECT_DIR=$(dirname "$GRADLEW")
          cd "$PROJECT_DIR"

          ./gradlew assembleDebug
